version: '3.8'

services:
  postgres:
    image: postgres:16.4
    restart: always
    environment:
      # Явно задаём — НЕ через ${}, чтобы TimeWeb не потерял.
      - POSTGRES_DB=n8n
      # 👉 unique_user - замените на своё значение
      - POSTGRES_USER=unique_user
      # 👉 strong_password - замените на своё значение
      - POSTGRES_PASSWORD=strong_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # Проверка здоровья базы — ОК
      test: ['CMD-SHELL', 'pg_isready -U admindev']
      interval: 5s
      timeout: 5s
      retries: 5

  n8n:
    image: ghcr.io/n8n-io/n8n:latest
    restart: always
    environment:
      # Слушаем на всех интерфейсах и нужном порту.
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678

      # База — явно прописаны те же значения, что и в Postgres.
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=n8n
      # 👉 unique_user - замените на своё значение (тоже самое что и для postgress)
      - DB_POSTGRESDB_USER=unique_user
       # 👉 strong_password - замените на своё значение (тоже самое что и для postgress)
      - DB_POSTGRESDB_PASSWORD=password

      # 👉 Правильный публичный URL, выданный TimeWeb, например https://repo_name-timeweb-000.twc1.net
      - WEBHOOK_URL=

      # Отключаем телеметрию.
      - N8N_DIAGNOSTICS_ENABLED=false

    ports:
      - "5678:5678"

    volumes:
      - n8n_data:/n8n

    depends_on:
      postgres:
        condition: service_healthy

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5678/healthz']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
# Явное указание пути для создания тома с данными, что бы информация сохранялась после перезагрузки.
  postgres_data:
    name: postgres_data_global
  n8n_data:
    name: n8n_data_global
