version: '3.8'

services:
  postgres:
    image: postgres:16.4
    restart: always
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=admin_dev
      - POSTGRES_PASSWORD=clockwerck12
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  n8n:
    image: ghcr.io/n8n-io/n8n:latest
    restart: always
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=admin_dev
      - DB_POSTGRESDB_PASSWORD=clockwerck12
      - WEBHOOK_URL=https://rmay1er-n8n-timeweb-e42d.twc1.net/
      - N8N_DIAGNOSTICS_ENABLED=false
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/n8n
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:5678/healthz']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  n8n_data:
